Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,7 +49,15 @@ jobs:
       
       - run:
           name: "Unzip dist.zip"
-          command: sshpass -p $FTP_PASSWORD ssh $FTP_USER@$FTP_HOST "sudo apt install unzip; if [ ! -f $FTP_TARGET_DIR/dist.zip ]; then echo "File not found" && exit 1; else rm -rf !($FTP_TARGET_DIR/*.zip) && unzip dist.zip -d $FTP_TARGET_DIR; fi"
+          command: | 
+            sshpass -p $FTP_PASSWORD ssh $FTP_USER@$FTP_HOST "
+              sudo apt install unzip; 
+              if [ ! -f $FTP_TARGET_DIR/dist.zip ]; 
+                then echo "File not found" && exit 1; 
+              else
+                shopt -s extglob 
+                rm -rf !($FTP_TARGET_DIR/*.zip) && unzip $FTP_TARGET_DIR/dist.zip -d $FTP_TARGET_DIR;
+              fi"
 
 
 
